<!DOCTYPE html>
<html>
<head>
    <title>Local Font Loading &amp; Caching</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel='stylesheet' href='dist/css/main.css' type='text/css' media='all' />
</head>
<body>

<main class="main">
    <article class="article">
        <h1 class="article__title">
            Entstehung der Arten/Fünftes Kapitel
        </h1>
        <p class="article__source">
            Veröffentlicht auf <a href="https://de.wikisource.org/wiki/Entstehung_der_Arten/F%C3%BCnftes_Kapitel">WikiSource</a>
        </p>

        <div class="article__content">
            <p class="hint">
                Dies ist eine Demonstation einer Technologie zum asyncronen Laden von Schriften. Den Quellcode findest du auf <a href="https://github.com/bitstarr/localfont">Github</a>.
            </p>
            <p>Wirkungen äusserer Bedingungen. — Gebrauch und Nichtgebrauch der Organe in Verbindung mit Natürlicher Züchtung; — Flieg- und Seh-Organe. — Akklimatisirung. — Wechselbeziehungen des Wachsthums. — Kompensation und Ökonomie der Entwickelung. — Falsche Wechselbeziehungen. — Vielfache, rudimentäre und wenig entwickelte Organisationen sind veränderlich. — In ungewöhnlicher Weise entwickelte Theile sind sehr veränderlich; — spezifische mehr als Sippen-Charaktere. — Sekundäre Geschlechts-Charaktere veränderlich. — Zu einer Sippe gehörige Arten variiren auf analoge Weise. — Rückkehr zu längst verlornen Charakteren. — Summarium.</p>
            <p>Ich habe bisher von den Abänderungen — die so gemein und manchfaltig im Kultur-Stande der Organismen und in etwas minderem Grade häufig in der freien Natur sind — zuweilen so gesprochen, als ob dieselben vom Zufall veranlasst wären. Diess ist aber eine ganz unrichtige Ausdrucks-Weise, welche nur geeignet ist unsre gänzliche Unwissenheit über die Ursache jeder besonderen Abweichung zu beurkunden. Einige Schriftsteller sehen es mehr als die Aufgabe des Reproduktiv-Systemes an, individuelle Verschiedenheiten oder ganz leichte Abweichungen des Baues hervorzubringen, als das Kind den Ältern gleich zu machen. Aber die viel grössere Veränderlichkeit sowohl als die viel häufigeren Monstrositäten der der Kultur unterworfenen Organismen leiten mich zur Annahme, dass Abweichungen der Struktur in irgend einer Weise von der Beschaffenheit der äusseren Lebens-Bedingungen, welchen die Ältern und deren Vorfahren mehre Generationen lang ausgesetzt gewesen sind, abhängen. Ich habe im ersten Kapitel die Bemerkung gemacht — doch würde ein langes Verzeichniss von Thatsachen, welches hier nicht gegeben werden kann, dazu nöthig seyn, die Wahrheit dieser Bemerkung zu beweisen —, dass das Reproduktiv-System für Veränderungen in den äussern Lebens-Bedingungen äusserst empfindlich ist; daher ich dessen funktionellen Störungen in den Ältern hauptsächlich die veränderliche oder bildsame Beschaffenheit ihrer Nachkommenschaft zuschreibe. Die [143] männlichen und weiblichen Elemente der Organisation scheinen davon schon berührt zu seyn vor deren Vereinigung zur Bildung neuer Abkömmlinge der Spezies. Was die Spielpflanzen (S. 15) anbelangt, so wird die Knospe allein betroffen, die auf ihrer ersten Entwickelungs-Stufe von einem Ei’chen nicht sehr wesentlich verschieden ist. Dagegen sind wir in gänzlicher Unwissenheit darüber, wie es komme, dass durch Störung des Reproduktiv-Systems dieser oder jener Theil mehr oder weniger als ein andrer berührt werde. Demungeachtet gelingt es uns hier und da einen schwachen Lichtstrahl aufzufangen, und wir halten uns überzeugt, dass es für jede Abänderung irgend eine wenn auch geringe Ursache geben müsse.</p>
            <p>Wie viel unmittelbaren Einfluss Verschiedenheiten in Klima, Nahrung u. s. w. auf irgend ein Wesen auszuüben vermögen, ist äusserst zweifelhaft. Ich bin überzeugt, dass bei Thieren die Wirkung äusserst gering, bei Pflanzen vielleicht etwas grösser seye. Man kann wenigstens mit Sicherheit sagen, dass diese Einflüsse nicht die vielen trefflichen und zusammengesetzten Anpassungen der Organisation eines Wesens ans andre hervorgebracht haben können, welche wir in der Natur überall erblicken. Einige kleine Wirkungen mag man dem Klima, der Nahrung u. s. w. zuschreiben, wie z. B. Edward Forbes sich mit Bestimmtheit darüber ausspricht, dass eine Konchylien-Art in wärmeren Gegenden und seichtem Wasser glänzendere Farben als in ihren kälteren Verbreitungs-Bezirken annehmen kann. Gould glaubt, dass Vögel derselben Art in einer stets heiteren Atmosphäre glänzender gefärbt sind, als auf einer Insel oder an der Küste[1]. So glaubt auch Wollaston, dass der Aufenthalt in der Nähe des Meeres die Farben der Insekten angreife. Moquin-Tandon gibt eine Liste von Pflanzen, welche an der See-Küste mehr und weniger fleischige Blätter bekommen, wenn sie auch landeinwärts [144] nicht fleischig sind. Und so liessen sich noch manche ähnliche Beispiele anführen.</p>
            <p>Die Thatsache, dass Varietäten einer Art, wenn sie in die Verbreitungs-Zone einer andern Art hinüberreichen, in geringem Grade etwas von deren Charakteren annehmen, stimmt mit unsrer Ansicht überein, dass Spezies aller Art nur ausgeprägtere bleibende Varietäten sind. So haben die Konchylien-Arten seichter tropischer Meeres-Gegenden gewöhnlich glänzendere Farben als die in tiefen und kalten Gewässern wohnenden. So sind die Vögel-Arten der Binnenländer nach Gould lebhafter als die der Inseln gefärbt. So sind die Insekten-Arten, welche auf die Küsten beschränkt sind, oft Bronze-artig und trüb von Aussehen wie jeder Sammler weiss. Pflanzen-Arten, welche nur längs dem Meere fortkommen, sind sehr oft mit fleischigen Blättern versehen. Wer an die besondre Erschaffung einer jeden einzelnen Spezies glaubt, wird daher sagen müssen, dass z. B. diese Konchylien für ein wärmeres Meer mit glänzenderen Farben geschaffen worden sind, während jene andern die lebhaftere Färbung erst durch Abänderung angenommen haben, als sie in die seichteren und wärmeren Gewässer übersiedelten.</p>
            <p>Wenn eine Abänderung für ein Wesen von geringstem Nutzen ist, vermögen wir nicht zu sagen, wie viel davon von der häufenden Thätigkeit der Natürlichen Züchtung und wie viel von dem Einfluss äussrer Lebens-Bedingungen herzuleiten ist. So ist es den Pelz-Händlern wohl bekannt, dass Thiere einer Art um so dichtere und bessere Pelze besitzen, in je kälterem Klima sie gelebt haben. Aber wer vermöchte zu sagen, wie viel von diesem Unterschied davon herrühre, dass die am wärmsten gekleideten Einzelwesen durch Natürliche Züchtung viele Generationen hindurch begünstigt und erhalten worden sind, und wie viel von dem direkten Einflusse des strengen Klimas? Denn es scheint wohl, dass das Klima einige unmittelbare Wirkung auf die Beschaffenheit des Haares unsrer Hausthiere ausübe.</p>
            <p>Man kann Beispiele anführen, dass dieselbe Varietät unter den aller-verschiedensten Lebens-Bedingungen entstanden ist, während andrerseits verschiedene Varietäten einer Spezies unter [145] gleichen Bedingungen zum Vorschein kommen[2]. Diese Thatsachen zeigen, wie mittelbar die Lebens-Bedingungen wirken. So sind jedem Naturforscher auch zahllose Beispiele von sich ächt erhaltenden Arten ohne alle Varietäten bekannt, obwohl dieselben in den entgegengesetztesten Klimaten leben. Derartige Betrachtungen veranlassen mich, nur ein sehr geringes Gewicht auf den direkten Einfluss der Lebens-Bedingungen zu legen. Indirekt scheinen sie, wie schon gesagt worden, einen wichtigen Antheil an der Störung des Reproduktiv-Systemes zu nehmen und hiedurch Veränderlichkeit herbeizuführen, und Natürliche Züchtung spart dann alle nützliche wenn auch geringe Abänderung zusammen, bis solche vollständig entwickelt und für uns wahrnehmbar wird.</p>
            <p>Wirkungen von Gebrauch und Nichtgebrauch.) Die im ersten Kapitel angeführten Thatsachen lassen wenig Zweifel bei unseren Hausthieren übrig, dass Gebrauch gewisse Theile stärke und ausdehne und Nichtgebrauch sie schwäche, und dass solche Abänderungen vererblich sind. In der freien Natur hat man keinen Maassstab zur Vergleichung der Wirkungen lang forgesetzten Gebrauches oder Nichtgebrauches, weil wir die älterlichen Formen nicht kennen; doch tragen manche Thiere Bildungen an sich, die sich als Folge des Nichtgebrauchs erklären lassen. Professor R. Owen hat bemerkt, dass es eine grosse Anomalie in der Natur ist, dass ein Vogel nicht fliegen könne, und doch sind mehre in dieser Lage. Die Südamerikanische Dickkopf-Ente kann nur über der Oberfläche des Wassers hinflattern und hat Flügel von fast der nämlichen Beschaffenheit wie die Aylesburger Hausenten-Rasse. Da die grossen Boden-Vögel selten zu andren Zwecken fliegen, als um einer Gefahr zu entgehen, so glaube ich, dass die fast ungeflügelte Beschaffenheit verschiedener Vögel-Arten, welche einige Inseln des Grossen Ozeans jetzt bewohnen oder einst bewohnt haben, wo sie keine Verfolgung von Raubthieren zu gewärtigen haben, vom Nichtgebrauche ihrer Flügel herrührt. Der Strauss bewohnt zwar Kontinente und ist von Gefahren bedroht, denen er nicht durch Flug [146] entgehen kann; aber er kann sich selbst durch Ausschlagen mit den Füssen gegen seine Feinde so gut vertheidigen wie einige der kleineren Vierfüsser. Man kann sich vorstellen, dass der Urvater des Strausses eine Lebens-Weise etwa wie der Trappe gehabt, und dass er in Folge Natürlicher Züchtung in einer langen Generationen-Reihe immer grösser und schwerer geworden seye, seine Beine mehr und seine Flügel weniger gebraucht habe, bis er endlich ganz unfähig geworden sey zu fliegen.</p>
            <p>Kirby hat bemerkt (und ich habe dieselbe Thatsache beobachtet), dass die Vordertarsen vieler männlichen Kothkäfer oft abgebrochen sind; er untersuchte siebenzehn Musterstücke seiner Sammlung, und fand in keinem eine Spur mehr davon. Onites Apelles hat seine Tarsen so gewöhnlich verloren, dass man diess Insekt beschrieben, als fehlten sie ihm gänzlich. In einigen anderen Sippen sind sie nur in verkümmertem Zustande vorhanden. Dem Ateuchus oder heiligen Käfer der Ägyptier fehlen sie gänzlich. Doch ist kein genügender Nachweis vorhanden, dass Verstümmelungen immer erblich seyen, und ich möchte den gänzlichen Mangel der Vordertarsen des Ateuchus und ihren verkümmerten Zustand in einigen andern Sippen lieber der lang-fortgesetzten Wirkung ihres Nichtgebrauches bei deren Stamm-Vätern zuschreiben; denn da die Tarsen vieler Kothkäfer meistens fehlen, so müssen sie schon früh im Leben verloren gehen und können daher bei diesen Insekten nicht viel gebraucht werden.</p>
            <p>In einigen Fällen möchten wir leicht dem Nichtgebrauche gewisse Abänderungen der Organisation zuschreiben, welche jedoch gänzlich oder hauptsächlich von Natürlicher Züchtung herrühren. Wollaston hat die merkwürdige Thatsache entdeckt, dass von den 550 Käfer-Arten, welche Madeira bewohnen, 200 so unvollkommene Flügel haben, dass sie nicht fliegen können, und dass von den 29 der Insel ausschliesslich angehörigen Sippen nicht weniger als 23 lauter solche Arten enthalten. Manche Thatsachen, wie unter andern, dass in vielen Theilen der Welt fliegende Käfer beständig ins Meer gewehet werden und zu Grunde gehen, dass die Käfer auf Madeira nach Wollaston's [147] Beobachtung meistens verborgen liegen, bis der Wind ruhet und die Sonne scheint, dass die Zahl der Flügel-losen Käfer an den ausgesetzten kahlen Felsklippen verhältnissmässig grösser als in Madeira selbst ist, und zumal die ausserordentliche Thatsache, worauf Wollaston so beharrlich fusset, dass gewisse grosse anderwärts sehr zahlreiche Käfer-Gruppen, welche durch ihre Lebens-Weise viel zu fliegen genöthigt sind, auf Madeira gänzlich fehlen, — diese mancherlei Gründe machen mich glauben, dass die ungeflügelte Beschaffenheit so vieler Käfer dieser Insel hauptsächlich von Natürlicher Züchtung, doch wahrscheinlich in Verbindung mit Nichtgebrauch herrühre. Denn während tausend aufeinanderfolgender Generationen wird jeder einzelne Käfer, der am wenigsten fliegt, entweder weil seine Flügel am wenigsten entwickelt sind oder weil er der indolenteste ist, die meiste Aussicht haben alle andern zu überleben, weil er nicht ins Meer gewehet wird; und auf der andern Seite werden diejenigen Käfer, welche am liebsten fliegen, am öftesten in die See getrieben und vernichtet werden.</p>
            <p>Diejenigen Insekten auf Madeira dagegen, welche sich nicht am Boden aufhalten und, wie die an Blumen lebenden Käfer und Schmetterlinge, von ihren Flügeln gewöhnlich Gebrauch machen müssen um ihren Unterhalt zu gewinnen, haben nach Wollaston's Vermuthung keinesweges verkümmerte, sondern vielmehr stärker entwickelte Flügel. Diess ist ganz verträglich mit der Thätigkeit der Natürlichen Züchtung. Denn, wenn ein neues Insekt zuerst auf die Insel kommt, wird das Streben der Natürlichen Züchtung die Flügel zu verkleinern oder zu vergrössern davon abhängen, ob eine grössre Anzahl von Individuen durch erfolgreiches Ankämpfen gegen die Winde, oder durch mehr und weniger häufigen Verzicht auf diesen Versuch sich rettet. Es ist derselbe Fall wie bei den Matrosen eines in der Nähe der Küste gestrandeten Schiffes; für diejenigen, welche gut schwimmen, ist es um so besser, je besser sie schwimmen könnten um ihr Heil im Weiterschwimmen zu versuchen, während es für die schlechten Schwimmer am besten wäre, wenn sie gar nicht schwimmen könnten und sich daher auf dem Wrack Rettung suchten. [148]</p>
            <p>Die Augen der Maulwürfe und einiger wühlenden Nager sind an Grösse verkümmert und in manchen Fallen ganz von Haut und Pelz bedeckt. Dieser Zustand der Augen rührt wahrscheinlich von fortwährendem Nichtgebrauche her, dessen Wirkung vielleicht durch Natürliche Züchtung unterstützt wird. Ein Süd-Amerikanischer Nager, Ctenomys, hat eine noch mehr unterirdische Lebensweise als der Maulwurf, und ein Spanier, welcher oft dergleichen gefangen, versicherte mir, dass solcher oft ganz blind seye; einer, den ich lebend bekommen, war es gewiss und zwar, wie die Sektion ergab, in Folge einer Entzündung der Nickhaut. Da häufige Augen-Entzündungen einem jeden Thiere nachtheilig werden müssen, und da für unterirdische Thiere die Augen gewiss nicht unentbehrlich sind, so wird eine Verminderung ihrer Grösse, die Verwachsung des Augenlides damit und die Überziehung derselben mit dem Felle für sie von Nutzen seyn; und wenn Diess der Fall, so wird Natürliche Züchtung die Wirkung des Nichtgebrauches beständig unterstützen.</p>
        </div>
    </article>
</main>

    <script>
        // Awesome localStorage font caching
        var basePath = '/';
        <?php include 'dist/js/localfont.js'; ?>
    </script>

</body>
</html>
